OBJS-$(CONFIG_AFIR_FILTER)                   += aarch64/af_afir_init.o
OBJS-$(CONFIG_EQ_FILTER)                     += aarch64/vf_eq_init.o
OBJS-$(CONFIG_BLEND_FILTER)                  += aarch64/vf_blend_init_aarch64.o
OBJS-$(CONFIG_BWDIF_FILTER)                  += aarch64/vf_bwdif_init_aarch64.o
OBJS-$(CONFIG_COLORDETECT_FILTER)            += aarch64/vf_colordetect_init.o
OBJS-$(CONFIG_NLMEANS_FILTER)                += aarch64/vf_nlmeans_init.o
OBJS-$(CONFIG_SCENE_SAD)                     += aarch64/scene_sad_init.o
OBJS-$(CONFIG_THRESHOLD_FILTER)              += aarch64/vf_threshold_init.o

NEON-OBJS-$(CONFIG_AFIR_FILTER)              += aarch64/af_afir_neon.o
NEON-OBJS-$(CONFIG_EQ_FILTER)                += aarch64/vf_eq_neon.o
NEON-OBJS-$(CONFIG_BLEND_FILTER)             += aarch64/vf_blend_neon.o
NEON-OBJS-$(CONFIG_BWDIF_FILTER)             += aarch64/vf_bwdif_neon.o
NEON-OBJS-$(CONFIG_COLORDETECT_FILTER)       += aarch64/vf_colordetect_neon.o
NEON-OBJS-$(CONFIG_NLMEANS_FILTER)           += aarch64/vf_nlmeans_neon.o
NEON-OBJS-$(CONFIG_SCENE_SAD)                += aarch64/scene_sad_neon.o
NEON-OBJS-$(CONFIG_THRESHOLD_FILTER)         += aarch64/vf_threshold_neon.o
